# This function is to download the data file only once and process the unzipped file
# only once. 
# This script calls the downloadCache function once to initialize the 'cache' list variable in the
# Global Environment.
# WARNING: Do not run this script more than once. It will cause the cached data frame to be set to NULL
# again causing the call to subsequent plot[1-4] function calls to re-download the data files.

downloadCache <- function(x){
    
    # Function to save the data frame
    setCache <- function(y){
        x <<- y
    } 
    
    # Function to retrieve the processed data frame
    getCache <- function() x
    
    # Function to generate the processes data frame
    download <- function(){
        temp <- tempfile()
        download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",
                      temp, method = "curl")
        unzip(temp, "household_power_consumption.txt")
        
        # The pipe method redirects the lines generated by the awk tool to readLines function.
        # awk code to only read the required rows ,i.e, rows dated 1 Feb 2007 to 2 Feb 2007.
        connection <- readLines(pipe("
                                     awk '{
                                     split($0, line, \";\");
                                if(line[1] == \"1/2/2007\" || line[1] == \"2/2/2007\")
                                    print $0
                             }
                             ' household_power_consumption.txt"))
        
        # Determine the classes of the columns beforehand
        classes <- c("character", "character", rep("numeric", 7))
        
        # Convert the output from readLines to a textConnection for read.csv
        dat <- read.csv(tconn <- textConnection(connection), header = FALSE, sep = ";", colClasses = classes)
        
        # Adding the names to the data frame
        names(dat) <- c("Date","Time", "Global_active_power", "Global_reactive_power", "Voltage",
                        "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
        
        # Closing the textConnection
        close(tconn)
        
        # Deleting the temporary file
        unlink(temp)
        
        # Formatting the Date and Time columns and return the data frame
        dat$Date <- strptime(dat$Date, "%d/%m/%Y")
        dat$Time <- strptime(paste(dat$Date, dat$Time), "%Y-%m-%d %H:%M:%S")
        dat
    }
    
    # Return the list of all functions
    list(setCache = setCache, getCache = getCache, download = download)
}

# To load the 'cache' list into the Global Environment
# This variable has to be passed to all the Plot functions.
cache <- downloadCache(NULL)
